spring:
  application:
    name: words

  datasource:
    url: jdbc:postgresql://localhost:5432/words?serverTimezone=Asia/Shanghai
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Shanghai

  sql:
    init:
      mode: always
      schema-locations: classpath:db/migration/V1__init_word_vocabulary.sql,classpath:db/migration/V2__create_dictionary_tables.sql,classpath:db/migration/V3__add_dictionary_creation_type.sql
      continue-on-error: true


server:
  port: 8080

logging:
  level:
    com.example.words: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
    org.springframework.web.servlet.handler.SimpleUrlHandlerMapping: TRACE
  file:
    name: logs/app.log
    max-size: 10MB
    max-history: 7
